Style change
sh1mot4ku/GDS pull request #39
Opened 2021-12-10 03:38 UTC by Sh11ntar0

Changed the Style Sheet.
Please check it.

2021-12-10 04:03 UTC, BlackStone8960 approved these changes
Looks good, thank you for doing such a good job!

2021-12-12 03:17 UTC, miyabitanimchi requested changes
Thank you for your great job! There was one thing I noticed, but the errors below occur when you go to the about page.
<img width="554" alt="スクリーンショット 2021-12-11 午後7 04 43" src="https://user-images.githubusercontent.com/69213541/145698773-979005f6-b177-42ca-8c54-11f976480ecc.png">
<img width="555" alt="スクリーンショット 2021-12-11 午後7 04 49" src="https://user-images.githubusercontent.com/69213541/145698775-5c5fe123-158d-4989-8491-8e3291d936f5.png">
<img width="562" alt="スクリーンショット 2021-12-11 午後7 04 56" src="https://user-images.githubusercontent.com/69213541/145698779-c5be03c7-b57b-4ead-8edd-0e4e1676ee93.png">

As the errors say, in React they should be `strokeWidth`, `strokeLinecap` and `strokeLineJoin` respectively.
Please check the suggested changes below as well, thank you!

2021-12-12 03:17 UTC, miyabitanimchi commented on src/components/AboutPage/AboutPage.js
> +                stroke-linejoin="round"
```suggestion
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
```

2021-12-12 03:17 UTC, miyabitanimchi commented on src/components/AboutPage/AboutPage.js
> +                stroke-width="1.5"
```suggestion
                strokeWidth="1.5"
```

2021-12-13 00:36 UTC, Sh11ntar0 commented
I fixed the errors that Miyabi told me about.

2021-12-15 23:51 UTC, merged